### ISSUE TITLE
When I add the package to meteor I get exception on compilation.

### ISSUE THREAD

**Issue by alekkowalczyk** [c0cky/react-masonry-meteor#1]
This is the exception:

=> Modified -- restarting.
W20151122-19:09:30.149(1)? (STDERR)
W20151122-19:09:30.150(1)? (STDERR) C:\Users\alek\AppData\Local\.meteor\packages
\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibe
rs\future.js:245
W20151122-19:09:30.151(1)? (STDERR)
throw(ex);
W20151122-19:09:30.151(1)? (STDERR)
      ^
W20151122-19:09:30.151(1)? (STDERR) ReferenceError: React is not defined
W20151122-19:09:30.151(1)? (STDERR)     at Package (react-masonry-meteor.js:4:20
)
W20151122-19:09:30.151(1)? (STDERR)     at C:\!a7Project\quicknotes-app\.meteor\
local\build\programs\server\packages\camrongodbout_react-masonry-meteor.js:206:4

W20151122-19:09:30.152(1)? (STDERR)     at C:\!a7Project\quicknotes-app\.meteor\
local\build\programs\server\packages\camrongodbout_react-masonry-meteor.js:213:3

W20151122-19:09:30.152(1)? (STDERR)     at C:\!a7Project\quicknotes-app\.meteor\
local\build\programs\server\boot.js:242:10
W20151122-19:09:30.152(1)? (STDERR)     at Array.forEach (native)
W20151122-19:09:30.152(1)? (STDERR)     at Function._.each._.forEach (C:\Users\a
lek\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_b
undle\server-lib\node_modules\underscore\underscore.js:79:11)
W20151122-19:09:30.152(1)? (STDERR)     at C:\!a7Project\quicknotes-app\.meteor\
local\build\programs\server\boot.js:137:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by c0cky** [comment]
It says that React is not defined. I'll add react as a dependency to the package.

**Comment by c0cky** [comment]
fixed in c1eee3c904da4741854cfbfda8d6701247d6f1d0
